my first site
Vitalya26/Spint3 pull request #1
Opened 2022-04-03 12:49 UTC by Vitalya26

2022-04-03 15:07 UTC, studenttsu requested changes
Привет! Очень даже хорошо для начала! 🙂

Есть что поправить:
- Нужно отработать по комментариям
- Перестать использовать фиксированные размеры ширины, высоты (на лекции объяснял почему это плохо). Да и как будете адаптировать вёрстку под мобильные устройства при жёстких значениях?
- Проверить стили по макету
![image](https://user-images.githubusercontent.com/12005449/161434452-3d09e223-9b66-4f11-afc9-866250d986f7.png)

2022-04-03 15:07 UTC, studenttsu commented on Untitled-1.html
> +            <div class="container4">
Нужно отказаться от дублирования реализации каждого блока, перечисления. Пойти по пути универсальной разметки (показывал на занятии https://github.com/studenttsu/ra-fontend-4stream/blob/main/src/index.html)

```HTML
<section class="section">
    <div class="container">

        <div class="section__header">
            <h2 class="section__title">Title</h2>
            <p class="section__subtitle">Description</p>
        </div>

        <div class="section__inner">
            some content
        </div>

    </div>
</section>
```

2022-04-03 15:07 UTC, studenttsu commented on Untitled-1.html
В блоке "Популярные услуги" нужно переписать названия селекторов в разметке. Сейчас названия не привязаны к контексту, очень универсальные. В реальной разработке так не делают

Хотя по БЭМ там всё корректно!

Вот пример:

```
<section class="section">
                <div class="container">
            
                    <div class="section__header">
                        <h2 class="section__title">Популярные услуги</h2>
                    </div>
            
                    <div class="section__inner">
                        <div class="benefits-wrap">
                            <div class="benefit">
                                <div class="benefit__icon">
                                    <img src="./images/man.png" alt="" />
                                </div>
                                <div class="benefit__title">Маникюр</div>
                                <div class="benefit__text">Аппаратный, комбинированный или классический.</div>
                                <button class="benefit__button"> <p>Записаться</p></button>
                            </div>

                            ... 
                        </div>
                    </div>
            
                </div>
            </section>
```

2022-04-13 14:34 UTC, Vitalya26 commented
Sprint 3

2022-04-13 14:37 UTC, merged